
package oracle.demo.oow.bd.loader.analytics;

/**
 * This class is used to refresh the recommendations for a specific customer.
 * It uses the recommendations that were generated by Oracle Advanced Analytics
 * in Oracle Database.
 */

public class MovieRecommendationRefresh {

    public MovieRecommendationRefresh() {
        super();
    }

    /**
     *Refreshes the recommendations for a customer.
     * @param args The customer id that will be refreshed.
     */
    public static void main(String[] args) {
        MovieRecommendationRefresh mu = new MovieRecommendationRefresh();
        
        if (args.length != 1) {
            System.out.println("A single customer id is required in order to refresh recommendations.");
            System.exit(0);
        }

        // UserItemLoader loads recommendations from a file or from the database.                        
        UserItemLoader uit = new UserItemLoader();

        try {
            int custId = Integer.parseInt(args[0]);
            uit.refreshCustomerRecommendations(custId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    } //main

}
